create table public.solicitudes (
  id bigint generated by default as identity not null,
  iniciada_por_id uuid not null,
  tipo text not null,
  equipo_id uuid null,
  nombre_equipo text null,
  escudo_url text null,
  estado text not null,
  motivo text null,
  respuesta_admin text null,
  fecha_creacion timestamp without time zone not null default now(),
  fecha_respuesta timestamp without time zone null,
  jugador_objetivo_id uuid null,
  capitan_objetivo_id uuid null,
  admin_aprobador_id uuid null,
  aprobado_jugador boolean null,
  aprobado_capitan boolean null,
  aprobado_admin boolean null,
  constraint solicitudes_pkey primary key (id),
  constraint solicitudes_id_key unique (id),
  constraint solicitudes_capitan_objetivo_id_fkey foreign KEY (capitan_objetivo_id) references usuarios (id),
  constraint solicitudes_usuario_id_fkey foreign KEY (iniciada_por_id) references usuarios (id),
  constraint solicitudes_jugador_objetivo_id_fkey foreign KEY (jugador_objetivo_id) references usuarios (id),
  constraint solicitudes_equipo_id_fkey foreign KEY (equipo_id) references equipos (id),
  constraint solicitudes_admin_aprobador_id_fkey foreign KEY (admin_aprobador_id) references usuarios (id),
  constraint tipo_check check (
    (
      tipo = any (
        array[
          'crear_equipo'::text,
          'unirse_equipo'::text,
          'baja_equipo'::text,
          'disolver_equipo'::text,
          'expulsar_jugador'::text
        ]
      )
    )
  ),
  constraint estado_check check (
    (
      estado = any (
        array[
          'pendiente'::text,
          'aceptada'::text,
          'rechazada'::text
        ]
      )
    )
  )
) TABLESPACE pg_default;